version: '3.8'

# The default docker-compose.override file can use the "localhost" as the external name for testing web apps within the same dev machine.
# The EMAILPROCESSORSYSTEM_EXTERNAL_DNS_NAME_OR_IP environment variable is taken, by default, from the ".env" file defined like:
#     EMAILPROCESSORSYSTEM_EXTERNAL_DNS_NAME_OR_IP=localhost
# but values present in the environment vars at runtime will always override those defined inside the .env file

services:
  maildev:
    ports:
      - '5500:1080'
      - '1025:1025'

  rabbitmq:
    ports:
      - '5672:5672'

  redis:
    image: redis:alpine
    ports:
      - '5379:6379'

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - '5433:1433'
    volumes:
      - sqldata:/var/opt/mssql

  zipkin:
    ports:
      - '5411:9411'

  fake-oracle-fetch-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - RetryMigrations=true
    ports:
      - '5101:80'
      - '50002:50001'

  fake-oracle-fetch-api-dapr:
    command:
      [
        './daprd',
        '-app-id',
        'fake-oracle-fetch-api',
        '-app-port',
        '80',
        '-components-path',
        '/components',
        '-config',
        '/configuration/config.yaml',
      ]
    volumes:
      - './dapr/components/:/components'
      - './dapr/configuration/:/configuration'

  webstatus:
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - HealthChecksUI__HealthChecks__0__Name=Fake Oracle Fetch Api
      - HealthChecksUI__HealthChecks__0__Uri=http://fake-oracle-fetch-api/hc
    ports:
      - '5107:80'

  dapr-placement:
    command: ['./placement', '-port', '50000', '-log-level', 'debug']
    ports:
      - '50000:50000'

volumes:
  sqldata:
    external: false
