version: '3.8'

services:
  maildev:
    image: maildev/maildev:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: redis:alpine

  # Use the Azure SQL Edge version so we can also run on Apple Sillicon (thanks @ChristianWeyer)
  sqldata:
    image: mcr.microsoft.com/azure-sql-edge

  zipkin:
    image: openzipkin/zipkin-slim:latest

  fake-oracle-fetch-api:
    image: ${REGISTRY:-emailprocessorsystem}/fakeoraclefetchapi:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Services/FakeOracleFetchApi/Dockerfile
    depends_on:
      - sqldata

  fake-oracle-fetch-api-dapr:
    image: 'daprio/daprd:latest'
    network_mode: 'service:fake-oracle-fetch-api'
    depends_on:
      - fake-oracle-fetch-api

  webstatus:
    image: ${REGISTRY:-emailprocessorsystem}/webstatus:${TAG:-latest}
    build:
      context: .
      dockerfile: src/Web/Webstatus/Dockerfile

  dapr-placement:
    image: 'daprio/dapr:latest'
