// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using FakeOracleFetchApi.Infrastructure;

#nullable disable

namespace FakeOracleFetchApi.Migrations
{
    [DbContext(typeof(OracleDbContext))]
    [Migration("20240412181804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailQueue", b =>
                {
                    b.Property<int>("EmailQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailQueueId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("XslName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailQueueId");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailQueues");

                    b.HasData(
                        new
                        {
                            EmailQueueId = 11502,
                            Email = "aangepast@email.adr",
                            EmailTemplateId = 1,
                            XslName = "LOGIN"
                        },
                        new
                        {
                            EmailQueueId = 11503,
                            Email = "dizzel@dizzel.dizz",
                            EmailTemplateId = 2,
                            XslName = "LOGIN"
                        },
                        new
                        {
                            EmailQueueId = 11504,
                            Email = "aangepast@email.adr",
                            EmailTemplateId = 7,
                            XslName = "OVERDUE"
                        },
                        new
                        {
                            EmailQueueId = 11505,
                            Email = "dizzel@dizzel.dizz",
                            EmailTemplateId = 8,
                            XslName = "OVERDUE"
                        },
                        new
                        {
                            EmailQueueId = 11506,
                            Email = "aangepast@email.adr",
                            EmailTemplateId = 5,
                            XslName = "REPORT"
                        },
                        new
                        {
                            EmailQueueId = 11507,
                            Email = "dizzel@dizzel.dizz",
                            EmailTemplateId = 6,
                            XslName = "REPORT"
                        },
                        new
                        {
                            EmailQueueId = 11508,
                            Email = "aangepast@email.adr",
                            EmailTemplateId = 3,
                            XslName = "USER"
                        },
                        new
                        {
                            EmailQueueId = 11509,
                            Email = "dizzel@dizzel.dizz",
                            EmailTemplateId = 4,
                            XslName = "USER"
                        });
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplate");

                    b.HasDiscriminator<string>("Discriminator").HasValue("EmailTemplate");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailTemplates.Login", b =>
                {
                    b.HasBaseType("FakeOracleFetchApi.Model.EmailTemplate");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Login");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "2024-04-12",
                            Environment = "Production",
                            FullName = "John Doe",
                            Time = "20:18:03"
                        },
                        new
                        {
                            Id = 2,
                            Date = "2024-04-12",
                            Environment = "Production",
                            FullName = "Gerrit Janssen",
                            Time = "20:18:03"
                        });
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailTemplates.Overdue", b =>
                {
                    b.HasBaseType("FakeOracleFetchApi.Model.EmailTemplate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverdueDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EmailTemplate", t =>
                        {
                            t.Property("FullName")
                                .HasColumnName("Overdue_FullName");
                        });

                    b.HasDiscriminator().HasValue("Overdue");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            OrderCode = "ORDER1",
                            OrderDate = "2024-04-05",
                            OverdueDate = "2024-04-12",
                            ProductName = "Product X",
                            ProductNumber = "PROD1"
                        },
                        new
                        {
                            Id = 8,
                            Email = "gerrit.janssen@example.com",
                            FullName = "Gerrit Janssen",
                            OrderCode = "ORDER2",
                            OrderDate = "2024-04-05",
                            OverdueDate = "2024-04-12",
                            ProductName = "Product Y",
                            ProductNumber = "PROD2"
                        });
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailTemplates.Report", b =>
                {
                    b.HasBaseType("FakeOracleFetchApi.Model.EmailTemplate");

                    b.Property<string>("PortalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Report");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            PortalName = "Portal X",
                            ReportName = "Monthly Sales Report",
                            Url = "http://example.com/reports/monthly-sales"
                        },
                        new
                        {
                            Id = 6,
                            PortalName = "Portal Y",
                            ReportName = "Monthly Sales Report",
                            Url = "http://example.com/reports/monthly-sales"
                        });
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailTemplates.User", b =>
                {
                    b.HasBaseType("FakeOracleFetchApi.Model.EmailTemplate");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EmailTemplate", t =>
                        {
                            t.Property("Email")
                                .HasColumnName("User_Email");

                            t.Property("FullName")
                                .HasColumnName("User_FullName");

                            t.Property("Url")
                                .HasColumnName("User_Url");
                        });

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Company = "Example Company",
                            Email = "john.doe@example.com",
                            FullName = "John Doe",
                            ImageHeader = "header.jpg",
                            Password = "password123",
                            Url = "http://example.com",
                            UserName = "johndoe"
                        },
                        new
                        {
                            Id = 4,
                            Company = "Example Company",
                            Email = "gerrit.janssen@example.com",
                            FullName = "Gerrit Janssen",
                            ImageHeader = "header.jpg",
                            Password = "password123",
                            Url = "http://example.com",
                            UserName = "gerritjanssen"
                        });
                });

            modelBuilder.Entity("FakeOracleFetchApi.Model.EmailQueue", b =>
                {
                    b.HasOne("FakeOracleFetchApi.Model.EmailTemplate", "EmailTemplate")
                        .WithMany()
                        .HasForeignKey("EmailTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmailTemplate");
                });
#pragma warning restore 612, 618
        }
    }
}
